### ISSUE TITLE
Commands not responding or working

### ISSUE THREAD

**Issue by charan-24** [Shubhamrawat5/whatsapp-bot-ts#1]
i have followed the steps given in the Readme and a bot was also initialzed on the given whatsapp number but the commands are not responding/working and i am getting an error like this 
`Adding default milestones
Login data updated!
/workspaces/whatsapp-bot-ts/src/functions/addDefaultMilestone.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
TypeError: Cannot read properties of undefined (reading 'participants')
    at /workspaces/whatsapp-bot-ts/src/functions/addDefaultMilestone.js:21:24
    at Generator.next (<anonymous>)
    at fulfilled (/workspaces/whatsapp-bot-ts/src/functions/addDefaultMilestone.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by Shubhamrawat5** [comment]
It's fixed now. You can try now by taking latest commit pull

**Comment by charan-24** [comment]
Thank's bro 
It's working now
